services:
  postgres:
    image: postgres:16
    container_name: mercadopro-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mercadopro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - mercadopro_data:/var/lib/postgresql/data

volumes:
  mercadopro_data:
