const API_URL=(import.meta.env.VITE_API_URL||"http://localhost:8000")+"/api";
async function request(path,options={}){const token=localStorage.getItem("mercadopro_token");const headers={"Content-Type":"application/json",...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const r=await fetch(`${API_URL}${path}`,{...options,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||"Não foi possível concluir a operação.");return d}
export const api={
 login:(username,password)=>request("/auth/login",{method:"POST",body:JSON.stringify({username,password})}),me:()=>request("/auth/me"),dashboard:()=>request("/dashboard/summary"),
 products:(q="",category="",brand="",status="")=>request(`/products?q=${encodeURIComponent(q)}${category?`&category_id=${category}`:""}${brand?`&brand_id=${brand}`:""}${status?`&stock_status=${status}`:""}`),
 saveProduct:(data,id)=>request(id?`/products/${id}`:"/products",{method:id?"PATCH":"POST",body:JSON.stringify(data)}),
 categories:(q="")=>request(`/categories?q=${encodeURIComponent(q)}`),brands:(q="")=>request(`/brands?q=${encodeURIComponent(q)}`),units:()=>request("/categories/units"),
 createCategory:name=>request("/categories",{method:"POST",body:JSON.stringify({name})}),createBrand:name=>request("/brands",{method:"POST",body:JSON.stringify({name})}),
 inventorySummary:()=>request("/inventory/summary"),movement:data=>request("/inventory/movements",{method:"POST",body:JSON.stringify(data)}),
 suppliers:(q="")=>request(`/suppliers?q=${encodeURIComponent(q)}`),
 saveSupplier:(data,id)=>request(id?`/suppliers/${id}`:"/suppliers",{method:id?"PATCH":"POST",body:JSON.stringify(data)}),
 toggleSupplier:(id,active)=>request(`/suppliers/${id}/status?active=${active}`,{method:"PATCH"}),
 purchases:(params={})=>request(`/purchases?${new URLSearchParams(params).toString()}`),
 purchase:(id)=>request(`/purchases/${id}`),
 savePurchase:(data,id)=>request(id?`/purchases/${id}`:"/purchases",{method:id?"PATCH":"POST",body:JSON.stringify(data)}),
 finalizePurchase:(id)=>request(`/purchases/${id}/finalize`,{method:"POST"}),
 cancelPurchase:(id)=>request(`/purchases/${id}/cancel`,{method:"POST"}),
 supplierProduct:(data)=>request('/supplier-products',{method:'POST',body:JSON.stringify(data)}),
 customers:(q="")=>request(`/customers?q=${encodeURIComponent(q)}`),
 saveCustomer:(data,id)=>request(id?`/customers/${id}`:"/customers",{method:id?"PATCH":"POST",body:JSON.stringify(data)}),
 toggleCustomer:(id,active)=>request(`/customers/${id}/status?active=${active}`,{method:"PATCH"}),
 sales:(q="")=>request(`/sales?q=${encodeURIComponent(q)}`),
 sale:(id)=>request(`/sales/${id}`),
 createSale:(data)=>request("/sales",{method:"POST",body:JSON.stringify(data)}),
 finalizeSale:(id,payments)=>request(`/sales/${id}/finalize`,{method:"POST",body:JSON.stringify(payments)}),
 cancelSale:(id)=>request(`/sales/${id}/cancel`,{method:"POST"}),
 cashStatus:()=>request("/cash/status"),
 openCash:(opening_amount)=>request("/cash/open",{method:"POST",body:JSON.stringify({opening_amount})}),
 cashMovement:(data)=>request("/cash/movement",{method:"POST",body:JSON.stringify(data)}),
 closeCash:(closing_amount)=>request("/cash/close",{method:"POST",body:JSON.stringify({closing_amount})}),
 cashHistory:()=>request("/cash/history"),
 financeSummary:()=>request("/finance/summary"),
 financeCategories:(type="")=>request(`/finance/categories${type?`?entry_type=${type}`:""}`),
 createFinanceCategory:(data)=>request("/finance/categories",{method:"POST",body:JSON.stringify(data)}),
 financeEntries:(params={})=>request(`/finance/entries?${new URLSearchParams(params).toString()}`),
 createFinanceEntry:(data)=>request("/finance/entries",{method:"POST",body:JSON.stringify(data)}),
 payFinanceEntry:(id)=>request(`/finance/entries/${id}/pay`,{method:"POST"}),
 cancelFinanceEntry:(id)=>request(`/finance/entries/${id}/cancel`,{method:"POST"}),
 cashFlow:()=>request("/finance/cash-flow"),
 reportsSales:(start,end)=>request(`/reports/sales?${new URLSearchParams({...(start?{start}:{}),...(end?{end}:{})}).toString()}`),
 reportsProducts:(start,end,limit=10)=>request(`/reports/products?${new URLSearchParams({...(start?{start}:{}),...(end?{end}:{}),limit}).toString()}`),
 reportsStock:()=>request("/reports/stock"),
 reportsFinance:()=>request("/reports/finance"),
 reportsPurchases:(start,end)=>request(`/reports/purchases?${new URLSearchParams({...(start?{start}:{}),...(end?{end}:{})}).toString()}`),
 securityOverview:()=>request("/security/overview"), securityUsers:(q="")=>request(`/security/users?q=${encodeURIComponent(q)}`), createSecurityUser:data=>request("/security/users",{method:"POST",body:JSON.stringify(data)}), updateSecurityUser:(id,data)=>request(`/security/users/${id}`,{method:"PATCH",body:JSON.stringify(data)}), changePassword:data=>request("/security/password",{method:"POST",body:JSON.stringify(data)}), securityPermissions:(role="")=>request(`/security/permissions${role?`?role=${encodeURIComponent(role)}`:""}`), saveSecurityPermission:data=>request("/security/permissions",{method:"PUT",body:JSON.stringify(data)}), auditHistory:(params={})=>request(`/security/audit?${new URLSearchParams(params).toString()}`), securitySettings:()=>request("/security/settings"), updateSecuritySetting:(key,value)=>request(`/security/settings/${encodeURIComponent(key)}?value=${encodeURIComponent(value)}`,{method:"PUT"}),
 integrationsOverview:()=>request("/integrations/overview"),
 saveIntegration:(key,data)=>request(`/integrations/config/${encodeURIComponent(key)}`,{method:"PUT",body:JSON.stringify(data)}),
 createDevice:data=>request("/integrations/devices",{method:"POST",body:JSON.stringify(data)}),
 updateDevice:(id,data)=>request(`/integrations/devices/${id}`,{method:"PATCH",body:JSON.stringify(data)}),
 testDevice:id=>request(`/integrations/devices/${id}/test`,{method:"POST"})
};
